### ISSUE TITLE
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0'

### ISSUE THREAD

**Issue by Honghe** [lf94/png2linetext#1]
Environment:
- Ubuntu 20.04
- rustc 1.43.1 (8d69840ab 2020-05-04)

Test file:
![2021](https://user-images.githubusercontent.com/1092722/106564515-46936100-6568-11eb-9b1b-882d3174ed0a.png)

Output:
```
$ RUST_BACKTRACE=1 ./target/debug/image2linetext ./inputs/2021.png        
🬹🬹🬹🬹🬹🬾🬾🬹🬾🬹🬹🬼 🭉🬾🭉🬹🬹🬹🬹🬹🭉🬹🬹🬹🬹🬹🭉🬾🬹🭉🬹🬹🬾🭉🬹🬾🭉🬹🬹🬹🬹🬾🮇████▋🮉🮇▋🮉▋🭁🬾🮇🭌🮇🮉████🬾🬹🬹🬹🬹🬹🬾 🬹 🬹🬹🬹🬞🬹🬾🭉🬹🬹🬹🬹🬹
🮉🮂🮂🮂🭖▍ 🭁🭁█🬁🮂🬹 🬀🮇🭡🮂🮂🮂█🮇█  🭨█ 🭨███🬁🬀█🭪 🮇   🭖▋🮇▋▂▂🭅▋🬞█🭝🬎🭙 🭤🬎🬏🮇🮉🭇▂🬏🮉▍🮉🭨██🭨▍████▍🬀🮉█▋🮇🭡🭖█🭖█
🮉🮉███▍██▍🬾🬹🬹🬹🭁🭌🬾▋🮉█▍█🮇█🮉███🮇██🭇🬼▂▂▂🭅🬏🮇▍██🮇▋🮇▋███▋🮉█▋🬾🭉🬹🬹🬹█🬾🮉🮇█▋🮉▍🮉🮉███▍██▍🬾🬹🬹🬹🭁🭌🬾▋🮉█▍█
🮉🮉███▍🭝🭒🭌🭐🮉█🭖██▍▋🮉█▍█🮇█🮉███🮇🮂 🭁▍██🮂🭖█🮇▍██🮇▋🮇▋███▋🮉 🭨█🭅█🭪🭨█▋🮉🮇█▋🮉▍🮉🭒██🭒▍▋🬞█ 🭅█▂🭅█▍▋🮉█▍█
🮉▂▂▂🭅▍🬏🮉  ▂🭅🭒█🬏🬼🭐▂▂▂█🮇█🬹🬹🬹█🭉🬾█  🭅█🭒█🬾🮇🬹🬹🬹🭁▋🮇🭐▂▂🭅▋🬞🮇🭝 ▂🭅🭝🭒 🬏🮉▂▂▂🭅▍🮉🬹🬹🬹🭁▍🬾🮉  🬹🭁🭒█◥🬾🭌🬹🬹🬹█
🬁🮂🮂🮂🮂🭗🬀🮉▍▋🬁🮂🭁█🬀🭗🮂🮂🮂🮂🮂🭤🬎🬎🬎🬎🬎🭤🭙█🮇▍  🭁█🭙🭤🬎🬎🬎🬎🭗   🮂🮂  🮇🭐🮉   🭁  🮂    🭗🬁🮂🮂🮂🮂🭗🬀🮉▍▋🬁🮂🭖█🭡🭗🮂🮂🮂🮂🮂
🮉██▂🭅▍▋🮉██🭅█🭅█🭐█▂🭅█▍█🮇█🬎🬎▂🭝🮇▍█🭒█🭅🭐🬎🭒 ▂▂█🬎🮇▋🮇██🬹🭁▋🮉🮇█🭒🭌█🭒██🭁🬹🭁█▋🮉▍🮉🬎🬎▂🭅🭙▋🮉🭒█🭅█🬎🭒🭐 ▂🭅🬎🭙█
🮉🬾🭉🭒█🬹 🭁🭁█🬎🭒🬾🭤🭒 🭒🭝🬹🬹🬎🮇█🬾 🭒🭌 🭁█🭁█🭖█🬾🭒█ 🭖 🬹 🭙🮇🭌🬾🭖█🬹 🭁🭌🭁🭡🭖🭌🬾🭖🭌🭖█🬹🬹🮂🭗🮉🬾🭉🭁█🬹 🭁🭁█ 🭖🬾🭨█ 🭖🭪🬹🬹
🬁🭖▋🮉🭁🭡▋🮉█🮂🮂🭢🮂🬀🭁█🭌  🮂🬹🬾🭢🭖▍██🭨▍█🭡 ▂  🮇███🭖🭪 🭖▍🮇█🭤🭒█🭙🮇█▍🬏🬞▂🬞🮇🭝🬎🭙🭒▂🬼🬎🭢🭖▋🭒██▍🮉█🭖 🬹🭖▋🮉██🭖█🭁🭖
 🭁▍🮇█▋🭁█🭌🭅🮇█ ▍█🭉🬾🭤🭒🭐🬹🬼🬞█🭤🭒█🭙🭅🭝🭅▋🮉█🭙🮇▋🭇🬏🭤🭒▂▂🭉🭁▋🭤🭒🭝🭉🭁◥🭁▍█🭌🭙🮉▍🭉🬾🭒█🬹🬾🭉🭁▍🭢█🭗🭁█ 🭁🮇█🬀🭗█🭉🬾🭢🭖🭌🬹
🮉🭒▋🮇██🭡🭒█ 🬎🭒🭁██▍▋🮇🮉██🮇█ 🬾🮉🭌🭁 🭁🭡 🮂█🬹🭁🬾🮇▍🮇██▋🮇🭡█🮇███🭨█🭖🭪🭨███🭐🮉▂🮉██▍🮉🮉▋🮇██🭐🭅█🮇▂🭅███🭅🭐▂🭒█🭒
🮉🬎▂🭅█▂🬎 🬎🬏🮉█▍██🬎🬎🭒🬏🮉 🮇█ 🬹🭁█🭝█🭖 🮉██🭖█████🭖▋🭗🮇▋🬎▂█▂🬎🬎🬎🬏🮇█▋🮉█🭝🬎🭒🭐🮉▍🮇🮉🬎🬹🭁█🬹🬎 🬎🬾🮉█▍██🬎🬎🭒 🮉
🬁🮂🮇🮉█🮂▋🭉🬹🭢🭗█🭡🭢🮂🮂🭉🭁█🭌▋ 🭤🭙🮇█🭡🭒▍🮇▋🭙🮇█🭙🬎🬎🭙🮇🭁██▍  🭇🮉█ 🭨🬼🬹🬾 🮉█ 🮂 🭇 🭁█🭁 🭢🮂🮇🮉█🮂▋🮇█🭢🭗█🭡🭢🮂🮂🮇🮉██▋
🮉▋███🭪🭨 🬏🬼███▂🮉▋🮉██🭡🭗🭤🬎🮉█🭒█ 🭙🬞▂🮇███▂🬎🭙███▍ 🮇█🮉███ ▍█🬾🮉██🭐🮉█🮇███🭗 🭤🮉█🭝█ 🭙🭇▂🬼███▂🬎🭙🮉██▋ 
🭇 🭒 🭒🭅🬏🬎🬎🮇███🬎🬞▂███▍  🭉◢🭒◥🭌🭌🬾🬎🭙🮉██🭝 🬹🭁███  🭉 🭖▋🭖🭁🬾🭢🮂🭗███🮂🬹🬹🭁██▋  🭉🭁🭖◥🭒█ 🬎🬎🮇███ 🭁🭌███🬞▂
🭢🮂🭢🭗🬁🮂🭌🬾 🭢🮂🭖🬀🮇🮉🮂🮂🭖█🬹🬹🭇   ▂ 🭖█▍🭢🬁🭖█🬀🬞█ 🭖███▋🭇▂▂▂▂🬏🬎🬎  🭇🬎🭙🭇🭅▋🬞🮇█🭒🬎🭙🭁█🭁🬹🭁 🬎🭙 🭢🭖🬎🭗🭉🭁🭖🭡🭖█🭒🬎
🮉████▍ 🭉🬹🬹🭅🬼 🮇█▍▋🮉█🮉🬼🮇█🬎🬎🬎█  🭇▂▂█🬏🭤🭒█🭤🭙█▋▂🬏🮇🭝🬎🬎🭒▋ 🭉🬹🬹🭁🭌🬾🭤🭒▋🭙🮇█ 🬹🬾🮉🮂🮂🮂🭖▍ 🭉🬹🬹🭁🬾 🭢🭖▍🬀🮉█🬁🬹
🮉🭁██🭁▍🮇██🬎🬎 🮉🮇🮉████▍🭗🮇█🬹🬹🬹█🭇🬹🭁🭡   🬾🬞█🬹🬹█🭌 🭗🮇▋███▋🮇██🮂🮂🮂🮉▍🮇████▋🬁🭗🮉🮉███▍🭅██🭇🬞▂🭅🭇🭅████▍▂
🮉🮉███▍▋🬞  🭅🬎🭙  🭙🮇🭝🭒🬼█🮇█🮉███🮇🭖█  🭁█ 🭁█🭡🮉██🮇▋🮇▋███▋🮉🭇  🭅🭝🭙🬞  🭙█🭒🬼🮉▍🮉🮉███▍▋◢  🭁🬎🭙◢◥🭙🮇🭝🭒🬾█
🮉 🬎🬎🭖▍▋🬎🭙🭌🭒🬾🮇█🮉🬾🮇🭌🭁 🭙🮇█🬁🮂🮂█🮇▍🮂🮇🭌🭖🬾🮇▋█▋🮉🭁🭡🮂🬀🮇🭐  🭨▋🮉  🮉🭖🭌🬾🮉🭅🭌🮉█🭁 🮂🭗🮉🬁🮂🮂🭖▍▋🬁🭗█🭖🭌🮇█🮉█🮇🭌█ 🮂
🮉████▍███🮂🮉█🮇███🭡🬁🮂🮉 🭤🬎🬎🬎🬎🬎🭤🬎🬎🭙🭤🬎🭙🭤🬎🬎🬎🭙 🭤🭙 🮇████▋🮉██🮂🬀🭒🭙🮉███🬀🬁🮇▍🭤🬎🬎🬎🬎🬎🭙🬎🬎🬎 🭤🬎🭤🬎🬎🬎🭙 🭤🭙
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/slice/mod.rs:2842:10
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:63
  14: <usize as core::slice::SliceIndex<[T]>>::index
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/slice/mod.rs:2842
  15: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/slice/mod.rs:2707
  16: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/liballoc/vec.rs:1890
  17: image2linetext::bitplane_to_linetext
             at src/main.rs:342
  18: image2linetext::main
             at src/main.rs:391
  19: std::rt::lang_start::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  20: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  21: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  23: std::panicking::try
             at src/libstd/panicking.rs:281
  24: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  25: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  26: std::rt::lang_start
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  27: main
  28: __libc_start_main
  29: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by lf94** [comment]
@Honghe yeah as mentioned the input image geometry must be divisible by 3, but also in RGBA 8bpc PNG format. I will fix this so it doesn't matter soon. At least you'll be able to test your QR code with this knowledge.

**Comment by lf94** [comment]
This is now fixed.
